version: "3.9"
services:
  master:
    image: mysql:8.4.1
    container_name: mysql-master
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./master/log:/var/log/mysql
      - ./master/data:/var/lib/mysql
      - ./master/conf:/etc/mysql/conf.d
    networks:
      - mysql-net

  slave:
    image: mysql:8.4.1
    container_name: mysql-slave
    restart: always
    depends_on:
      - master
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./slave/log:/var/log/mysql
      - ./slave/data:/var/lib/mysql
      - ./slave/conf:/etc/mysql/conf.d
    networks:
      - mysql-net

networks:
  mysql-net:
    driver: bridge
