// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: test.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CheckStatus_GetStatus_FullMethodName = "/pb.checkStatus/getStatus"
	CheckStatus_Health_FullMethodName    = "/pb.checkStatus/health"
)

// CheckStatusClient is the client API for CheckStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckStatusClient interface {
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TestMsg, error)
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type checkStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckStatusClient(cc grpc.ClientConnInterface) CheckStatusClient {
	return &checkStatusClient{cc}
}

func (c *checkStatusClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TestMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestMsg)
	err := c.cc.Invoke(ctx, CheckStatus_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkStatusClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CheckStatus_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckStatusServer is the server API for CheckStatus service.
// All implementations must embed UnimplementedCheckStatusServer
// for forward compatibility.
type CheckStatusServer interface {
	GetStatus(context.Context, *Empty) (*TestMsg, error)
	Health(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedCheckStatusServer()
}

// UnimplementedCheckStatusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckStatusServer struct{}

func (UnimplementedCheckStatusServer) GetStatus(context.Context, *Empty) (*TestMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedCheckStatusServer) Health(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCheckStatusServer) mustEmbedUnimplementedCheckStatusServer() {}
func (UnimplementedCheckStatusServer) testEmbeddedByValue()                     {}

// UnsafeCheckStatusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckStatusServer will
// result in compilation errors.
type UnsafeCheckStatusServer interface {
	mustEmbedUnimplementedCheckStatusServer()
}

func RegisterCheckStatusServer(s grpc.ServiceRegistrar, srv CheckStatusServer) {
	// If the following call pancis, it indicates UnimplementedCheckStatusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckStatus_ServiceDesc, srv)
}

func _CheckStatus_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckStatusServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckStatus_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckStatusServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckStatus_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckStatusServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckStatus_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckStatusServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckStatus_ServiceDesc is the grpc.ServiceDesc for CheckStatus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckStatus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.checkStatus",
	HandlerType: (*CheckStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getStatus",
			Handler:    _CheckStatus_GetStatus_Handler,
		},
		{
			MethodName: "health",
			Handler:    _CheckStatus_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
