version: '3.8'
services:
  postgres:
    hostname: postgres
    restart: always
    image: postgres:13
    container_name: postgres
    privileged: true
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      kong-net:
        ipv4_address: 172.20.0.2
  kong:
    restart: always
    image: kong:2.5.0-ubuntu
    platform: linux/arm64/v8
    container_name: kong
    privileged: true
    ports:
      - 8001:8001
      - 8000:8000
      - 8443:8443
      - 8444:8444
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - postgres
    networks:
      kong-net:
        ipv4_address: 172.20.0.3
    #command: [ "kong", "migrations", "bootstrap" ]
  konga:
    image: albertwzp/konga-arm64:next #开发环境arm64，生产环境用amd64
    environment:
      TOKEN_SECRET: my-secret
      NODE_ENV: production
    ports:
      - 8080:1337
    networks:
      kong-net:
        ipv4_address: 172.20.0.4
    depends_on:
      - postgres
networks:
  kong-net:
    ipam:
      config:
        - subnet: 172.20.0.0/24
