version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql_single_node
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msmall
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_conf:/etc/mysql/conf.d
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
