version: '3.5'
# 服务容器配置
services:
  etcd1:           # 自定义容器名称
    image: bitnami/etcd:latest
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:                               # 设置端口映射
      - "12379:2379"
      - "12380:2380"
    networks:
      etcd-cluster-net:
        ipv4_address: 10.4.0.2
    restart: always

  etcd2: # 自定义容器名称
    image: bitnami/etcd:latest
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports: # 设置端口映射
      - "22379:2379"
      - "22380:2380"
    networks:
      etcd-cluster-net:
        ipv4_address: 10.4.0.3
    restart: always

  etcd3: # 自定义容器名称
    image: bitnami/etcd:latest
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports: # 设置端口映射
      - "32379:2379"
      - "32380:2380"
    networks:
      etcd-cluster-net:
        ipv4_address: 10.4.0.4
    restart: always

  etcdkeeper:
    image: evildecay/etcdkeeper:latest
    container_name: etcdkeeper
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    networks:
      etcd-cluster-net:
        ipv4_address: 10.4.0.5
    ports:
      - "38080:8080"
    #environment:
    # ETCD keeper 不需要额外的配置，直接通过 WEB 界面连接 ETCD 集群
    restart: always
    command:
      - -h=0.0.0.0
      - -p=8080
      - -skiptls
      - -e=http://10.4.0.2:2379,http://10.4.0.3:2379,http://10.4.0.4:2379

# 网络配置
networks:
  etcd-cluster-net:
    ipam:
      config:
        - subnet: 10.4.0.0/24
