version: '3.1'
services:
  # redis1配置
  redis1:
    image: redis:6.0.4
    container_name: redis-1
    restart: always
    volumes:
      - ./redis-1/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 172.16.1.1
  # redis2配置
  redis2:
    image: redis:6.0.4
    container_name: redis-2
    restart: always
    volumes:
      - ./redis-2/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 172.16.1.2
  # redis3配置
  redis3:
    image: redis:6.0.4
    container_name: redis-3
    restart: always
    volumes:
      - ./redis-3/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 172.16.1.3
  # redis4配置
  redis4:
    image: redis:6.0.4
    container_name: redis-4
    restart: always
    volumes:
      - ./redis-4/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 172.16.1.4
  # redis5配置
  redis5:
    image: redis:6.0.4
    container_name: redis-5
    restart: always
    volumes:
      - ./redis-5/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 172.16.1.5
  # redis6配置
  redis6:
    image: redis:6.0.4
    container_name: redis-6
    restart: always
    volumes:
      - ./redis-6/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 172.16.1.6

# 网络配置
networks:
  redis-cluster-net:
    ipam:
      config:
        - subnet: 172.16.0.0/16
